// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/spotahome/kooper/examples/pod-terminator-operator/v2/apis/chaos/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePodTerminators implements PodTerminatorInterface
type FakePodTerminators struct {
	Fake *FakeChaosV1alpha1
}

var podterminatorsResource = v1alpha1.SchemeGroupVersion.WithResource("podterminators")

var podterminatorsKind = v1alpha1.SchemeGroupVersion.WithKind("PodTerminator")

// Get takes name of the podTerminator, and returns the corresponding podTerminator object, and an error if there is any.
func (c *FakePodTerminators) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PodTerminator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(podterminatorsResource, name), &v1alpha1.PodTerminator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodTerminator), err
}

// List takes label and field selectors, and returns the list of PodTerminators that match those selectors.
func (c *FakePodTerminators) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PodTerminatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(podterminatorsResource, podterminatorsKind, opts), &v1alpha1.PodTerminatorList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PodTerminatorList{ListMeta: obj.(*v1alpha1.PodTerminatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.PodTerminatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested podTerminators.
func (c *FakePodTerminators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(podterminatorsResource, opts))
}

// Create takes the representation of a podTerminator and creates it.  Returns the server's representation of the podTerminator, and an error, if there is any.
func (c *FakePodTerminators) Create(ctx context.Context, podTerminator *v1alpha1.PodTerminator, opts v1.CreateOptions) (result *v1alpha1.PodTerminator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(podterminatorsResource, podTerminator), &v1alpha1.PodTerminator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodTerminator), err
}

// Update takes the representation of a podTerminator and updates it. Returns the server's representation of the podTerminator, and an error, if there is any.
func (c *FakePodTerminators) Update(ctx context.Context, podTerminator *v1alpha1.PodTerminator, opts v1.UpdateOptions) (result *v1alpha1.PodTerminator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(podterminatorsResource, podTerminator), &v1alpha1.PodTerminator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodTerminator), err
}

// Delete takes name of the podTerminator and deletes it. Returns an error if one occurs.
func (c *FakePodTerminators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(podterminatorsResource, name, opts), &v1alpha1.PodTerminator{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePodTerminators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(podterminatorsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PodTerminatorList{})
	return err
}

// Patch applies the patch and returns the patched podTerminator.
func (c *FakePodTerminators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PodTerminator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(podterminatorsResource, name, pt, data, subresources...), &v1alpha1.PodTerminator{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PodTerminator), err
}
