// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PodTerminatorListerExpansion allows custom methods to be added to
// PodTerminatorLister.
type PodTerminatorListerExpansion interface{}
