// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	chaosv1alpha1 "github.com/spotahome/kooper/examples/pod-terminator-operator/v2/apis/chaos/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PodTerminatorLister helps list PodTerminators.
// All objects returned here must be treated as read-only.
type PodTerminatorLister interface {
	// List lists all PodTerminators in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*chaosv1alpha1.PodTerminator, err error)
	// Get retrieves the PodTerminator from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*chaosv1alpha1.PodTerminator, error)
	PodTerminatorListerExpansion
}

// podTerminatorLister implements the PodTerminatorLister interface.
type podTerminatorLister struct {
	listers.ResourceIndexer[*chaosv1alpha1.PodTerminator]
}

// NewPodTerminatorLister returns a new PodTerminatorLister.
func NewPodTerminatorLister(indexer cache.Indexer) PodTerminatorLister {
	return &podTerminatorLister{listers.New[*chaosv1alpha1.PodTerminator](indexer, chaosv1alpha1.Resource("podterminator"))}
}
