// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/spotahome/kooper/examples/pod-terminator-operator/v2/apis/chaos/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PodTerminatorLister helps list PodTerminators.
// All objects returned here must be treated as read-only.
type PodTerminatorLister interface {
	// List lists all PodTerminators in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PodTerminator, err error)
	// Get retrieves the PodTerminator from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.PodTerminator, error)
	PodTerminatorListerExpansion
}

// podTerminatorLister implements the PodTerminatorLister interface.
type podTerminatorLister struct {
	indexer cache.Indexer
}

// NewPodTerminatorLister returns a new PodTerminatorLister.
func NewPodTerminatorLister(indexer cache.Indexer) PodTerminatorLister {
	return &podTerminatorLister{indexer: indexer}
}

// List lists all PodTerminators in the indexer.
func (s *podTerminatorLister) List(selector labels.Selector) (ret []*v1alpha1.PodTerminator, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PodTerminator))
	})
	return ret, err
}

// Get retrieves the PodTerminator from the index for a given name.
func (s *podTerminatorLister) Get(name string) (*v1alpha1.PodTerminator, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("podterminator"), name)
	}
	return obj.(*v1alpha1.PodTerminator), nil
}
