apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pause-pods
  labels:
    application: pause
spec:
  replicas: 20
  selector:
    matchLabels:
      application: pause
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: pause
    spec:
      containers:
      - name: pause
        image: gcr.io/google_containers/pause-amd64:3.1
        imagePullPolicy: "Always"

---
apiVersion: chaos.spotahome.com/v1alpha1
kind: PodTerminator
metadata:
  name: pause
  labels:
    example: pod-terminator-operator
    operator: pod-terminator-operator
spec:
  selector:
    application: pause
  periodSeconds: 15
  terminationPercent: 10
  minimumInstances: 10
  #DryRun: true

