// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/spotahome/kooper/examples/pod-terminator-operator/v2/client/k8s/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// PodTerminators returns a PodTerminatorInformer.
	PodTerminators() PodTerminatorInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// PodTerminators returns a PodTerminatorInformer.
func (v *version) PodTerminators() PodTerminatorInformer {
	return &podTerminatorInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
