name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Execute the checks inside the container instead the VM.
    container: golangci/golangci-lint:v2.13.2-alpine
    steps:
      - uses: actions/checkout@v6
      - run: |
          ./hack/scripts/check.sh

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - run: make ci-unit-test

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [check, unit-test]
    strategy:
      matrix:
        kubernetes: [1.32.11, 1.33.12, 1.34.11, 1.35.8, 1.36.4]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: azure/setup-kubectl@v5
        with:
          version: v${{ matrix.kubernetes }}
      - name: Execute tests
        env:
          KIND_VERSION: v0.33.0
        run: |
          # Get dependencies.
          echo "Getting dependencies..."
          curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/

          # Start cluster.
          echo "Executing ${{ matrix.kubernetes }} Kubernetes tests..."
          KUBERNETES_VERSION=${{ matrix.kubernetes }} make ci-integration-test
